version: '3.8'

services:
  backend:
    build: ./backend
    container_name: securevote-backend
    ports:
      - "5000:5000"
    networks:
      - securevote
    restart: always

  frontend:
    image: nginx:alpine
    container_name: securevote-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - securevote

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - securevote

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - securevote

networks:
  securevote:
    driver: bridge
volumes:
  prometheus_data:
    driver: local

  grafana_data:
    driver: local