global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'securevote-backend'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'securevote-frontend'
    static_configs:
      - targets: ['frontend:80']